# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='filename',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
    ]
